steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

# Build the app
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-react-app'
  - '--image=gcr.io/$PROJECT_ID/my-react-app:$COMMIT_SHA'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--port=3000'

# Optionally, you can add a cleanup step to remove the Docker image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['rmi', 'gcr.io/$PROJECT_ID/my-react-app:$COMMIT_SHA']

images:
- 'gcr.io/$PROJECT_ID/my-react-app:$COMMIT_SHA'

# Set the logs bucket
options:
  logging: GCS_ONLY
  log_bucket: gs://$PROJECT_ID-cloudbuild-logs