steps:
  # Step 1: Install dependencies and build the React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend' # Directory containing your React app's package.json

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend' # Directory containing your React app's package.json

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/react-app'
      - '.'

  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/react-app'

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated' # Optional: Allow unauthenticated access if desired
