steps:
  - name: node:16
    entrypoint: npm
    args: ["run", "prep-npmrc"]

  - name: node:16
    entrypoint: npx
    args:
      - "google-artifactregistry-auth"
      - "--credential-config"
      - ".npmrc"
      - "--repo-config"
      - ".npmrc"

  - name: node:16
    entrypoint: npm
    args: ["ci"]

  - name: node:16
    entrypoint: npm
    args: ["run", "prettier:check"]

  - name: node:16
    entrypoint: npm
    args: ["run", "lint"]

  - name: node:16
    entrypoint: npm
    args: ["run", "build"]
